[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd server && npm install --legacy-peer-deps']

[phases.build]
cmds = ['cd server && npm run build']

[start]
cmd = 'cd server && npm start'

