[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

