# 📦 Configuração Nixpacks para Railway
# Twilio WhatsApp - SEM Chromium/Puppeteer

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
